const messageTypes = {
  JOIN_MESSAGE: "JOIN_MESSAGE",
  LEAVE_MESSAGE: "LEAVE_MESSAGE",
  TEXT_MESSAGE: "TEXT_MESSAGE",
  MY_MESSAGE: "MY_MESSAGE",
  FOREIGN_MESSAGE: "FOREIGN_MESSAGE"
  // IMAGE: "IMAGE",
  // AUDIO: "AUDIO",
  // VIDEO: "VIDEO",
  // GET_MEDIA: "GET_MEDIA",
  // INITIAL_MEDIA_MESSAGE: "INITIAL_MEDIA_MESSAGE",
};
export default messageTypes;
